

const Image = {
  logo: require("./PTX-Main-Logo.png"),
  bannerimage: require("./PTX-Official-banner.webp"),
  banner2: require("./Pages-background.webp"),
  service: require("./service.webp"),
  timing: require("./timing.webp"),
  tshirt: require("./polo-shirt.webp"),
  chat: require("./chat.webp"),
  Blog1: require("./Blog1-image.webp"),
  Blog2: require("./Blog2-image.webp"),
  Blog3: require("./Blog3-image.webp"),
  latestproduct1: require("./latestproduct1.jpg"),
  latestproduct2: require("./latestproduct2.jpg"),
  latestproduct3: require("./latestproduct3.jpg"),
  latestproduct4: require("./latestproduct4.webp"),
  latestproduct5: require("./latestproduct5.webp"),
  step1: require("./step1.webp"),
  step2: require("./step2.webp"),
  step3: require("./step3.webp"),
  Gallery1: require("./g1.jpeg"),
  Gallery2: require("./g2.png"),
  Gallery3: require("./g3.png"),
  Gallery4: require("./g4.jpeg"),
  Gallery5: require("./g5.jpeg"),
  Gallery6: require("./g6.jpeg"),
  p1: require("./Production1.webp"),
  p2: require("./Production2.webp"),
  p3: require("./Production3.webp"),
  p4: require("./Production4.webp"),
  p5: require("./Production5.webp"),
  p6: require("./Production6.webp"),
  p7: require("./Production7.webp"),
  p8: require("./Production8.webp"),
  p9: require("./Production9.webp"),
  p10: require("./Production10.webp"),
  p11: require("./Production11.webp"),
sectionbanner: require("./aboutbanner.webp"),
  Thumbnail:require("./thumbnail.webp"),
  CEO: require("./Davidjumani.webp"),
  location: require("./location.webp"),
  qualityassurance: require("./QA.webp"),
  FabricDivision: require("./fabricdivision.webp"),
  GarmentDivision: require("./Garmentdivision.webp"),
  DyeingandFinishing: require("./Dyeing.webp"),
  Stitching: require("./stitching.webp"),
  Sampling: require("./sampling.webp"),
  Cutting: require("./cutting.webp"),
  Finishing: require("./Finishing.webp"),
  Laboratory: require("./laboratory.webp"),
};
export default Image;
