const Image={
    logo:require('./PTX-Main-Logo.png'),
    slider1:require("./s1.webp"),
    slider2:require("./s2.webp"),
    slider3:require("./s3.webp"),
    slider4:require("./s4.webp"),
    slider5:require("./s5.webp"),
    slider6:require("./s6.webp"),
    image1:require("./1.webp"),
    image2:require("./2.webp"),
    image3:require("./3.webp"),
    image4:require("./4.webp"),
    image5:require("./5.webp"),
    image6:require("./6.webp"),
    image7:require("./7.webp"),
    image8:require("./8.webp"),
    image9:require("./8.webp"),
    sectionimage:require("./Sectionimage.webp"),
H1:require("./hoddie1.webp"),
H2:require("./hoddie2.webp"),
H3:require("./hoddie3.webp"),
H4:require("./hoddie4.webp"),
H5:require("./hoddie5.webp"),
H6:require("./hoddie6.webp"),
H7:require("./hoddie7.webp"),
H8:require("./hoddie8.webp"),
H9:require("./hoddie9.webp"),
H10:require("./hoddie10.webp"),

}
export default Image