const Image = {
  logo: require("./PTX-Main-Logo.png"),
  slider1: require("./Sliderimage-1.webp"),
  slider2: require("./SliderImage-2.webp"),
  slider3: require("./sliderimage-3.webp"),
  slider4: require("./Sliderimage-4.webp"),
  slider5: require("./Sliderimage-5.webp"),
  slider6: require("./Sliderimage-6.webp"),
  Blog1: require("./Blog-1.webp"),
  Blog2: require("./Stitch.webp"),
  Blog3:require("./Blog-3.webp"),
  latestproduct1: require("./latestproduct1.jpg"),
  latestproduct2: require("./latestproduct2.jpg"),
  latestproduct3: require("./latestproduct3.jpg"),
  step1: require("./step1.webp"),
  step2: require("./step2.webp"),
  step3: require("./step3.webp"),
  p1: require("./Production1.webp"),
  p2: require("./Production2.webp"),
  p3: require("./Production3.webp"),
  p4: require("./Production4.webp"),
  p5: require("./Production5.webp"),
  p6: require("./Production6.webp"),
  p7: require("./Production7.webp"),
  p8: require("./Production8.webp"),
  p9: require("./Production9.webp"),
  image1: require("./1.webp"),
  image2: require("./2.webp"),
  image3: require("./3.webp"),
  image4: require("./4.webp"),
  image5: require("./5.webp"),
  image6: require("./6.webp"),
  image7: require("./7.webp"),
  image8: require("./8.webp"),
  image9: require("./8.webp"),
  image10: require("./pt-1.webp"),
  image11: require("./pt-2.webp"),
  image12: require("./pt-3.webp"),
  image13: require("./pt-4.webp"),
  image14: require("./pt-5.webp"),
  image15: require("./pt-6.webp"),
  sectionimage: require("./sectionbanner.webp"),
CEO:require("./Davidjumani.webp"),
};
export default Image;
